### ISSUE TITLE
[DISCUSS] AutoCloseable

### ISSUE THREAD

**Issue by danielsoro** [JNOSQL/diana#57]
I think that some classes, like: CassandraDocumentEntityManager should implement AutoCloseable https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html. 

WDYT? :)

**Comment by otaviojava** [comment]
@danielsoro is already done, please, look to `ColumnFamilyManager`, the interface that CassandraDocumentEntityManager implements. It's already implements `AutoCloseable`

**Comment by danielsoro** [comment]
@otaviojava Yeh.. I can see here: https://github.com/JNOSQL/diana/blob/master/diana-api/src/main/java/org/jnosql/diana/api/CloseResource.java

Sorry for my mistake.
