### ISSUE TITLE
[DISCUSS] @author

### ISSUE THREAD

**Issue by danielsoro** [JNOSQL/diana#59]
No have sure, but we don't need to specify that @author if we want to be an apache projects.

**Comment by otaviojava** [comment]
You're right, we can remove it.

**Comment by Daniel-Dos** [comment]
I did not understand about the removal of the tag to become an Apache project.
Thank you.

**Comment by danielsoro** [comment]
@Daniel-Dos

With the ASF 2.0 license, @author tags is not allowed in any Apache source code. In all fairness, the Apache License 2.0 calls for a file to be included with the software that lists off all the contributors and copyright holders of the work. Also, all contributors to the ASF are required to sign an agreement giving copyright authority to the organization, so the organization is well within its legal rights. ASF's leaders believe that highlighting the contributions of committing members breeds ego and conflict in the community.

**Comment by Daniel-Dos** [comment]
I understand your explanation, thank you for the clarification @danielsoro.

**Comment by danielsoro** [comment]
You're welcome @Daniel-Dos.
Legal stuffs.

**Comment by danielsoro** [comment]
merged: https://github.com/JNOSQL/diana/pull/60
