### ISSUE TITLE
Create ReaderField implementations

### ISSUE THREAD

**Issue by otaviojava** [JNOSQL/diana#6]
The ReaderField has the goal read a information from Value by Class informated.

So, Create ReaderField implementation to:

- [x]  Number
- [x]  Character
- [x]  Boolean
- [x]  Enum
- [x]  String and CharSequence
- [ ]  java.util.Date
- [ ]  java.util.Calendar
- [ ]  java.time.Temporal
- [ ]  java.time.LocalDate
- [ ]  java.time.LocalDateTime
- [ ]  java.time.LocalTime
- [ ]  java.time.Year
- [ ]  java.time.YearMonth
- [ ]  java.time.ZonedDateTime
- [x]  Optional

Example: 

https://github.com/JNOSQL/diana/blob/master/diana-api/src/main/java/org/apache/diana/api/reader/NumberReader.java

https://github.com/JNOSQL/diana/blob/master/diana-api/src/test/java/org/apache/diana/api/reader/NumberReaderTest.java

**Comment by danielsoro** [comment]
@otaviojava Please, close that.
I had create new issues to organize better it: 
https://github.com/JNOSQL/diana/issues/9
https://github.com/JNOSQL/diana/issues/10
https://github.com/JNOSQL/diana/issues/11
https://github.com/JNOSQL/diana/issues/12
https://github.com/JNOSQL/diana/issues/13
https://github.com/JNOSQL/diana/issues/14
https://github.com/JNOSQL/diana/issues/15
https://github.com/JNOSQL/diana/issues/16
https://github.com/JNOSQL/diana/issues/17

:)

**Comment by otaviojava** [comment]
It makes sense
