### ISSUE TITLE
Move to Eclipse?

### ISSUE THREAD

**Issue by keilw** [JNOSQL/diana#79]
Is this repository going to stay under the JNOSQL organization or will it move to the Eclipse one?

**Comment by otaviojava** [comment]
We'll stay here.

**Comment by otaviojava** [comment]
@keilw  please send an email to each issue. There is a good point to start the discussion

**Comment by keilw** [comment]
This was about the GitHub organization, but if there's a committers mailing list, we can ask the question there (where Mentors like Wayne should also be CC)
