### ISSUE TITLE
Eclipse Naming conventions

### ISSUE THREAD

**Issue by keilw** [JNOSQL/diana#80]
Being accepted as Eclipse project, the package name space should be "org.eclipse.jnosql.*" not "org.jnosql.*"

**Comment by otaviojava** [comment]
Hello, Werner.
This move is a recommendation, I mean that isn't mandatory.
Let discuss it on email list.

**Comment by keilw** [comment]
I thought this has been answered quite clearly in several MP threads by Wayne & Co?

**Comment by otaviojava** [comment]
Yes, you're

**Comment by keilw** [comment]
Which mailing list btw, I guess that uses eclipse.org or something else?

**Comment by otaviojava** [comment]
https://dev.eclipse.org/mailman/listinfo/jnosql-dev
