### ISSUE TITLE
VERY bad license headers

### ISSUE THREAD

**Issue by keilw** [JNOSQL/diana#84]
Hi, 

this may have been due to an attempt of proposing Diana to Apache first, now it was accepted by Eclipse, but this license header is totally wrong:
```
  Copyright 2017 Eclipse Foundation
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements. See the NOTICE file
```

**Comment by keilw** [comment]
Whether it's 
`Copyright 2017 Otavio Santana and others`
or
`Copyright 2017 Tomitribe and others`
Mostly depends on which legal entity @otaviojava represents here (or rather as Eclipse Committer) but neither can Eclipse Foundation be used as the legal entity here nor has the ASF anything to do with it. Apache License is all there is about Apache.

**Comment by otaviojava** [comment]
Here I'm as an individual member.
I might put SouJava and others, WDYT?

**Comment by keilw** [comment]
No, if you are an Individual representing yourself at Eclipse Foundation, then it should be "Copyright Otavio Santana and others".
Even if SouJava unlike other JUGs was a Legal Entity (a "Foundation" like Eclipse or Apache) I don't think it can or should own IP of its own, but that I am sure @waynebeaton is happy to answer (or his IP team at Eclipse)

**Comment by otaviojava** [comment]
Ok, I'll fix it.

**Comment by otaviojava** [comment]
thanks @keilw  fixed
