### ISSUE TITLE
Release 0.0.1 latest release?

### ISSUE THREAD

**Issue by keilw** [JNOSQL/diana#88]
Hi,

The release https://github.com/JNOSQL/diana/releases/tag/0.0.1 claims to be the "Latest Release". Judging by the low version number isn't it more a pre-release so far? Maybe more honest to click that checkbox until probably even Graduation by Eclipse.

**Comment by otaviojava** [comment]
That is a good point until now that is the latest version...
Probably, we can release the newest version with a lot of fixes that we did on "0.0.1" te "0.0.2-incubating."

**Comment by keilw** [comment]
Yes, but the difference is the "preview" flag. Even if you set "0.0.2" or "0.0.2-incubating" to preview, the 0.0.1 one would be considered "Final" without that flag.
